version: '3.9'

services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=primeraBase
      - DB_USER=fjavierlasso
      - DB_PASSWORD=1234

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: primeraBase
      MYSQL_USER: fjavierlasso
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: root_password # Cambia esto por una contraseña segura para el usuario root
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
